apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: clusterapi-workload-1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: clusterapi-workload-1-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: clusterapi-workload-1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: clusterapi-workload-1
  namespace: default
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: clusterapi-workload-1-control-plane
  namespace: default
spec:
  region: ap-northeast-1
  sshKeyName: clusterapi-handson
  version: v1.28.0
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: clusterapi-workload-1-pool-0
  namespace: default
spec:
  clusterName: clusterapi-workload-1
  replicas: 3
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: clusterapi-workload-1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: clusterapi-workload-1-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: clusterapi-workload-1-pool-0
  namespace: default
spec: {}
