[package]
name = "make_public_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
quote = "1.0.36"
syn = { version = "2.0.70", features = ["extra-traits"] }
proc-macro2 = "1.0.86"
